# coding: utf-8
"""
Billing — webhook inbox types (PR 1: Lemon Squeezy Webhook Foundation).

The `WebhookEvent` dataclass is the portable in-memory shape both storage
backends (SQLite / Postgres) round-trip. It deliberately mirrors the
memory_plane taxonomy conventions:

  * TEXT primary key (uuid4 hex) generated by the store, ISO-8601 UTC
    timestamps — so the schema ports SQLite → Postgres without lossy
    conversions.
  * `payload_json` holds the VERIFIED raw request body (the authoritative
    copy a future processor re-parses). It is only ever persisted AFTER
    signature verification succeeds, so the inbox never stores forged data.
  * `dedup_key` is the SHA-256 of the raw body — a deterministic,
    secret-rotation-safe idempotency key. Lemon Squeezy retries the exact
    same bytes, so identical deliveries collide on the UNIQUE(provider,
    dedup_key) index and are ingested exactly once.

This module is pure data + small helpers — no I/O, no framework imports —
so it is safe to import from anywhere (routes, stores, future processors).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional


# ── Providers ────────────────────────────────────────────────────────────────
# Kept as an open string set (not an Enum) so a future provider (Stripe,
# Paddle, …) is added without a schema/enum migration. Lemon Squeezy is the
# only one wired in PR 1.
PROVIDER_LEMON_SQUEEZY = "lemon_squeezy"
DEFAULT_PROVIDER = PROVIDER_LEMON_SQUEEZY


# ── Lifecycle statuses ───────────────────────────────────────────────────────
# The inbox tracks a webhook event through an explicit lifecycle. PR 1 only
# advances an event as far as STORED (received + signature-verified +
# durably persisted). PROCESSING / PROCESSED / FAILED exist for the future
# consumer (entitlements, credits) that PR 1 intentionally does NOT build —
# the transitions are available so that consumer never has to alter this
# schema.
STATUS_RECEIVED = "received"     # transient — accepted, not yet persisted
STATUS_STORED = "stored"         # verified + persisted; awaiting processing
STATUS_PROCESSING = "processing"  # a consumer has claimed it (future PR)
STATUS_PROCESSED = "processed"   # consumer finished successfully (future PR)
STATUS_FAILED = "failed"         # consumer failed; safe to retry (future PR)

# The set a store will accept on a transition. Guards against a typo silently
# writing an unknown status.
VALID_STATUSES = frozenset({
    STATUS_RECEIVED, STATUS_STORED, STATUS_PROCESSING,
    STATUS_PROCESSED, STATUS_FAILED,
})

# Statuses a future processor is allowed to pick up (idempotent reprocessing).
REPROCESSABLE_STATUSES = frozenset({STATUS_STORED, STATUS_FAILED})


@dataclass
class WebhookEvent:
    """One inbound webhook delivery.

    The store owns `id`, `created_at`, `updated_at`, `received_at` — callers
    build a WebhookEvent with the payload-derived fields and the store fills
    the rest on insert. `attempts` counts processing attempts by future
    consumers, not HTTP retries.
    """
    # Identity / routing
    provider: str = DEFAULT_PROVIDER
    event_name: str = ""                     # meta.event_name / X-Event-Name
    resource_type: Optional[str] = None      # data.type   (e.g. "subscriptions")
    resource_id: Optional[str] = None        # data.id
    # Idempotency + integrity
    dedup_key: str = ""                       # sha256(raw body), hex
    signature: Optional[str] = None           # X-Signature header (audit only)
    payload_json: str = "{}"                  # verified raw body (JSON text)
    # Lifecycle
    status: str = STATUS_STORED
    processing_error: Optional[str] = None
    attempts: int = 0
    # Store-managed
    id: Optional[str] = None
    received_at: Optional[str] = None
    processed_at: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

    def to_public_dict(self, *, include_payload: bool = False) -> Dict[str, Any]:
        """Diagnostics-safe projection.

        The payload can carry customer PII (emails, names) so it is EXCLUDED
        by default — only the owner-only detail endpoint opts in with
        include_payload=True (and serves it no-store). The `signature` is a
        keyed HMAC digest, not a secret, but we still omit it from the list
        projection to keep it lean.
        """
        out: Dict[str, Any] = {
            "id": self.id,
            "provider": self.provider,
            "event_name": self.event_name,
            "resource_type": self.resource_type,
            "resource_id": self.resource_id,
            "status": self.status,
            "attempts": self.attempts,
            "processing_error": self.processing_error,
            "received_at": self.received_at,
            "processed_at": self.processed_at,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }
        if include_payload:
            out["signature"] = self.signature
            out["payload_json"] = self.payload_json
        return out


def parse_event_fields(payload: Dict[str, Any]) -> Dict[str, Optional[str]]:
    """Extract the routing fields from a parsed Lemon Squeezy payload.

    Lemon Squeezy webhook bodies are JSON:API shaped:

        {
          "meta": { "event_name": "subscription_created", "custom_data": {…} },
          "data": { "type": "subscriptions", "id": "12345", "attributes": {…} }
        }

    Everything here is best-effort and defensive — a malformed / partial
    payload yields empty fields rather than raising, because the store still
    wants to persist the (verified) delivery for diagnostics even when its
    shape is unexpected.
    """
    meta = payload.get("meta") if isinstance(payload, dict) else None
    data = payload.get("data") if isinstance(payload, dict) else None
    meta = meta if isinstance(meta, dict) else {}
    data = data if isinstance(data, dict) else {}

    event_name = str(meta.get("event_name") or "").strip()
    resource_type = str(data.get("type") or "").strip() or None
    rid = data.get("id")
    resource_id = str(rid).strip() if rid is not None and str(rid).strip() else None

    return {
        "event_name": event_name,
        "resource_type": resource_type,
        "resource_id": resource_id,
    }


__all__ = [
    "PROVIDER_LEMON_SQUEEZY", "DEFAULT_PROVIDER",
    "STATUS_RECEIVED", "STATUS_STORED", "STATUS_PROCESSING",
    "STATUS_PROCESSED", "STATUS_FAILED",
    "VALID_STATUSES", "REPROCESSABLE_STATUSES",
    "WebhookEvent", "parse_event_fields",
]
